# Generated by Django 5.2.8 on 2025-12-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFeatureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_data_id', models.BigIntegerField(db_index=True)),
                ('event_timestamp', models.DateTimeField()),
                ('current_price', models.FloatField(null=True)),
                ('previous_price', models.FloatField(null=True)),
                ('price_diff_abs', models.FloatField(null=True)),
                ('price_diff_pct', models.FloatField(null=True)),
                ('days_since_price_change', models.FloatField(null=True)),
                ('price_change_frequency_90d', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pricing_features',
                'indexes': [models.Index(fields=['pricing_data_id'], name='pricing_fea_pricing_2dcdbc_idx'), models.Index(fields=['event_timestamp'], name='pricing_fea_event_t_3821ea_idx')],
            },
        ),
    ]
