# Generated by Django 5.2.8 on 2025-12-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast_offline', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricingfeaturerecord',
            constraint=models.UniqueConstraint(fields=('pricing_data_id', 'event_timestamp'), name='uq_pricing_data_event'),
        ),
    ]
