# Generated by Django 5.2.8 on 2025-12-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feast_offline', '0002_pricingfeaturerecord_uq_pricing_data_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingfeaturerecord',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pricingfeaturerecord',
            name='days_since_price_change',
        ),
        migrations.RemoveField(
            model_name='pricingfeaturerecord',
            name='previous_price',
        ),
        migrations.RemoveField(
            model_name='pricingfeaturerecord',
            name='price_change_frequency_90d',
        ),
        migrations.RemoveField(
            model_name='pricingfeaturerecord',
            name='price_diff_abs',
        ),
        migrations.RemoveField(
            model_name='pricingfeaturerecord',
            name='price_diff_pct',
        ),
    ]
