# Generated by Django 5.2.9 on 2025-12-18 11:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The functional name of the engine.', max_length=255)),
                ('model_type', models.CharField(help_text='The algorithm or methodology used.', max_length=100)),
                ('version', models.CharField(help_text='e.g., 2025.12.18.01', max_length=50)),
                ('model_binary', models.FileField(upload_to='models/binaries/')),
                ('encoder_binary', models.FileField(blank=True, null=True, upload_to='models/encoders/')),
                ('feature_names', models.JSONField(help_text="Ordered list of columns: ['const', 'log_Vcpu', ...]")),
                ('log_transformed_features', models.JSONField(blank=True, default=list)),
                ('categorical_features', models.JSONField(blank=True, default=list)),
                ('r_squared', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('mape', models.FloatField(help_text='Mean Absolute Percentage Error.')),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('training_sample_size', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False, help_text="Is this the current 'Champion' for this name?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ML Engine',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ModelCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='model_registry.mlengine')),
            ],
        ),
    ]
