# Generated by Django 5.2.9 on 2025-12-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlengine',
            name='scaler_binary',
            field=models.FileField(blank=True, help_text='Feature scaler for models like Ridge', null=True, upload_to='models/scalers/'),
        ),
    ]
