# Generated by Django 5.2.8 on 2025-12-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='latest_version',
            field=models.BooleanField(default=True),
        ),
    ]
