# Generated by Django 5.2.10 on 2026-01-14 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_registry', '0002_mlengine_scaler_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlengine',
            name='timestamp_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the model was trained/created'),
            preserve_default=False,
        ),
    ]
