# Generated by Django 4.2.25 on 2025-10-28 20:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('aws', 'Amazon Web Services'), ('azure', 'Microsoft Azure'), ('gcp', 'Google Cloud Platform')], max_length=10, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('api_endpoint', models.URLField(blank=True, help_text='Optional API endpoint; for Infracost, all use same endpoint.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uses_infracost', models.BooleanField(default=True, help_text="Indicates whether this provider's pricing is sourced from Infracost")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloudService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('infracost_service', models.BooleanField(default=True, help_text='True if this service is sourced from Infracost API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('exchange_rate_to_usd', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='PricingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('on_demand', 'On-Demand'), ('reserved', 'Reserved'), ('spot', 'Spot'), ('committed_use', 'Committed Use'), ('pay_as_you_go', 'Pay-as-you-go')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='cloud_pricing.cloudprovider')),
            ],
            options={
                'unique_together': {('provider', 'region_code')},
            },
        ),
        migrations.CreateModel(
            name='PricingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_family', models.CharField(blank=True, max_length=100)),
                ('instance_type', models.CharField(blank=True, max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=50)),
                ('tenancy', models.CharField(blank=True, max_length=20)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('price_per_year', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('price_unit', models.CharField(blank=True, max_length=50)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('effective_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_api', models.CharField(blank=True, default='infracost', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_pricing.currency')),
                ('pricing_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_pricing.pricingmodel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_pricing.cloudprovider')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_pricing.region')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_pricing.cloudservice')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('pricing_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cloud_pricing.pricingdata')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('increase', 'Price Increase'), ('decrease', 'Price Decrease'), ('threshold', 'Price Threshold')], max_length=10)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('percentage_change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pricing_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_pricing.pricingdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cloudservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud_pricing.servicecategory'),
        ),
        migrations.AddField(
            model_name='cloudservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='cloud_pricing.cloudprovider'),
        ),
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_endpoint', models.URLField()),
                ('status_code', models.IntegerField()),
                ('response_time', models.DecimalField(decimal_places=3, max_digits=8)),
                ('records_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_pricing.cloudprovider')),
            ],
            options={
                'ordering': ['-called_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pricingdata',
            index=models.Index(fields=['provider', 'service', 'region'], name='cloud_prici_provide_82e4a5_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingdata',
            index=models.Index(fields=['instance_type'], name='cloud_prici_instanc_0469b6_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingdata',
            index=models.Index(fields=['effective_date'], name='cloud_prici_effecti_84a37f_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingdata',
            index=models.Index(fields=['is_active'], name='cloud_prici_is_acti_dea2e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cloudservice',
            unique_together={('provider', 'service_code')},
        ),
    ]
