# Generated by Django 5.2.8 on 2025-11-23 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPricingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(blank=True, help_text='Optional upstream id for dedupe', max_length=200, null=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('source_api', models.CharField(blank=True, default='infracost', max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='PricingData',
            new_name='NormalizedPricingData',
        ),
        migrations.RenameIndex(
            model_name='normalizedpricingdata',
            new_name='cloud_prici_provide_42a720_idx',
            old_name='cloud_prici_provide_82e4a5_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedpricingdata',
            new_name='cloud_prici_instanc_ef7ba2_idx',
            old_name='cloud_prici_instanc_0469b6_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedpricingdata',
            new_name='cloud_prici_effecti_b88ca4_idx',
            old_name='cloud_prici_effecti_84a37f_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedpricingdata',
            new_name='cloud_prici_is_acti_ee44b6_idx',
            old_name='cloud_prici_is_acti_dea2e4_idx',
        ),
        migrations.AddField(
            model_name='rawpricingdata',
            name='normalized',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_entries', to='cloud_pricing.normalizedpricingdata'),
        ),
        migrations.AddField(
            model_name='rawpricingdata',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_pricing', to='cloud_pricing.cloudprovider'),
        ),
        migrations.AddIndex(
            model_name='rawpricingdata',
            index=models.Index(fields=['provider', 'node_id'], name='cloud_prici_provide_124d10_idx'),
        ),
        migrations.AddIndex(
            model_name='rawpricingdata',
            index=models.Index(fields=['fetched_at'], name='cloud_prici_fetched_9f6b33_idx'),
        ),
    ]
