# Generated by Django 5.2.8 on 2025-11-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0003_alter_currency_exchange_rate_to_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudprovider',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cloudprovider',
            name='name',
            field=models.CharField(choices=[('aws', 'Amazon Web Services'), ('azure', 'Microsoft Azure'), ('gcp', 'Google Cloud Platform')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cloudservice',
            name='service_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate_to_usd',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='normalizedpricingdata',
            name='instance_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='normalizedpricingdata',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='normalizedpricingdata',
            name='price_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='normalizedpricingdata',
            name='tenancy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='alert_type',
            field=models.CharField(choices=[('increase', 'Price Increase'), ('decrease', 'Price Decrease'), ('threshold', 'Price Threshold')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingmodel',
            name='display_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingmodel',
            name='name',
            field=models.CharField(choices=[('on_demand', 'On-Demand'), ('reserved', 'Reserved'), ('spot', 'Spot'), ('committed_use', 'Committed Use'), ('pay_as_you_go', 'Pay-as-you-go')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_code',
            field=models.CharField(max_length=100),
        ),
    ]
