# Generated by Django 5.2.8 on 2025-11-27 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0004_alter_cloudprovider_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='raw_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_normalized', to='cloud_pricing.rawpricingdata'),
        ),
    ]
