# Generated by Django 5.2.8 on 2025-11-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0005_normalizedpricingdata_raw_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalizedpricingdata',
            name='raw_data',
        ),
    ]
