# Generated by Django 5.2.8 on 2025-11-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0008_alter_apicalllog_called_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpricingdata',
            name='digest',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='rawpricingdata',
            name='raw_json',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='rawpricingdata',
            index=models.Index(fields=['provider', 'node_id', 'digest'], name='idx_provider_node_digest'),
        ),
        migrations.AddConstraint(
            model_name='rawpricingdata',
            constraint=models.UniqueConstraint(fields=('provider', 'node_id', 'digest'), name='uq_provider_node_digest'),
        ),
    ]
