# Generated by Django 5.2.8 on 2025-12-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0009_rawpricingdata_digest_alter_rawpricingdata_raw_json_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='normalizedpricingdata',
            new_name='normalized__provide_120948_idx',
            old_name='cloud_prici_provide_42a720_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedpricingdata',
            new_name='normalized__instanc_3d02ac_idx',
            old_name='cloud_prici_instanc_ef7ba2_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedpricingdata',
            new_name='normalized__effecti_d200ba_idx',
            old_name='cloud_prici_effecti_b88ca4_idx',
        ),
        migrations.RenameIndex(
            model_name='normalizedpricingdata',
            new_name='normalized__is_acti_127657_idx',
            old_name='cloud_prici_is_acti_ee44b6_idx',
        ),
        migrations.AlterModelTable(
            name='normalizedpricingdata',
            table='normalized_pricing_data',
        ),
    ]
