# Generated by Django 5.2.8 on 2025-12-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0010_rename_cloud_prici_provide_42a720_idx_normalized__provide_120948_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pricehistory',
            table='price_history',
        ),
    ]
