# Generated by Django 5.2.9 on 2025-12-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0011_alter_pricehistory_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalizedpricingdata',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='normalizedpricingdata',
            name='price_per_hour',
        ),
        migrations.RemoveField(
            model_name='normalizedpricingdata',
            name='price_per_month',
        ),
        migrations.RemoveField(
            model_name='normalizedpricingdata',
            name='price_per_year',
        ),
        migrations.DeleteModel(
            name='PriceAlert',
        ),
    ]
