# Generated by Django 5.2.9 on 2025-12-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0012_remove_normalizedpricingdata_attributes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cloudservice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cloudservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cloudservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cloudservice',
            name='infracost_service',
        ),
        migrations.RemoveField(
            model_name='cloudservice',
            name='service_code',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
