# Generated by Django 5.2.9 on 2025-12-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0013_alter_cloudservice_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudservice',
            old_name='service_name',
            new_name='name',
        ),
    ]
