# Generated by Django 5.2.9 on 2025-12-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0014_rename_service_name_cloudservice_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region_code',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('provider', 'name')},
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_name',
        ),
    ]
