# Generated by Django 5.2.9 on 2025-12-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0015_rename_region_code_region_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pricingmodel',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='pricingmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
