# Generated by Django 5.2.9 on 2025-12-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0016_remove_pricingmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cloudservice',
            unique_together={('provider', 'name')},
        ),
    ]
