# Generated by Django 5.2.8 on 2025-12-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0017_alter_cloudservice_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='price_per_hour',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='price_per_month',
        ),
    ]
