# Generated by Django 5.2.8 on 2025-12-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0018_remove_pricehistory_price_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rawpricingdata',
            name='uq_provider_node_digest',
        ),
        migrations.RemoveIndex(
            model_name='rawpricingdata',
            name='cloud_prici_provide_124d10_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawpricingdata',
            name='idx_provider_node_digest',
        ),
        migrations.RemoveField(
            model_name='rawpricingdata',
            name='digest',
        ),
        migrations.RemoveField(
            model_name='rawpricingdata',
            name='node_id',
        ),
        migrations.AddField(
            model_name='rawpricingdata',
            name='product_hash',
            field=models.CharField(default='', help_text='Unique hash of the raw pricing entry for deduplication', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawpricingdata',
            name='raw_json',
            field=models.TextField(blank=True, help_text='Optional raw JSON payload for auditing/debugging', null=True),
        ),
        migrations.AddIndex(
            model_name='rawpricingdata',
            index=models.Index(fields=['provider', 'product_hash'], name='cloud_prici_provide_7e4642_idx'),
        ),
        migrations.AlterModelTable(
            name='rawpricingdata',
            table='cloud_pricing_rawpricingdata',
        ),
    ]
