# Generated by Django 5.2.8 on 2025-12-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0019_remove_rawpricingdata_uq_provider_node_digest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicalllog',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='apicalllog',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='apicalllog',
            name='response_time',
        ),
    ]
