# Generated by Django 5.2.8 on 2025-12-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0020_remove_apicalllog_error_message_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rawpricingdata',
            name='cloud_prici_provide_7e4642_idx',
        ),
        migrations.RemoveField(
            model_name='rawpricingdata',
            name='provider',
        ),
        migrations.AddIndex(
            model_name='rawpricingdata',
            index=models.Index(fields=['product_hash'], name='cloud_prici_product_9436f3_idx'),
        ),
    ]
