# Generated by Django 5.2.8 on 2025-12-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0021_remove_rawpricingdata_cloud_prici_provide_7e4642_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='term_length',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
