# Generated by Django 5.2.8 on 2025-12-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0022_normalizedpricingdata_term_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
