# Generated by Django 5.2.8 on 2025-12-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0023_normalizedpricingdata_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='normalizedpricingdata',
            index=models.Index(condition=models.Q(('price_per_unit__gt', 0)), fields=['price_per_unit'], name='idx_price_positive'),
        ),
    ]
