# Generated by Django 5.2.9 on 2025-12-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0024_normalizedpricingdata_idx_price_positive'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='normalizedpricingdata',
            name='normalized__instanc_3d02ac_idx',
        ),
        migrations.AddIndex(
            model_name='normalizedpricingdata',
            index=models.Index(fields=['provider', 'service', 'region'], name='idx_npd_prov_serv_reg')
        ),
        migrations.AddIndex(
            model_name='normalizedpricingdata',
            index=models.Index(fields=['provider', 'service', 'region', 'pricing_model', 'currency', 'product_family', 'instance_type', 'operating_system', 'tenancy', 'price_unit'], name='idx_npd_unique_combo'),
        ),
        migrations.AddIndex(
            model_name='normalizedpricingdata',
            index=models.Index(fields=['provider', 'service', 'region', 'pricing_model', 'currency', 'product_family', 'instance_type', 'operating_system', 'tenancy', 'price_unit', 'price_per_unit'], name='idx_npd_price_change_detection'),
        ),
        migrations.AddIndex(
            model_name='normalizedpricingdata',
            index=models.Index(fields=['raw_entry'], name='idx_npd_raw_entry'),
        ),
        migrations.AddIndex(
            model_name='normalizedpricingdata',
            index=models.Index(fields=['is_active', 'effective_date'], name='idx_npd_active_effective'),
        ),
        migrations.AddIndex(
            model_name='normalizedpricingdata',
            index=models.Index(fields=['source_api'], name='idx_npd_source_api'),
        ),
    ]
