# Generated by Django 5.2.9 on 2025-12-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0025_remove_normalizedpricingdata_normalized__instanc_3d02ac_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='normalizedpricingdata',
            name='normalized__provide_120948_idx',
        ),
    ]
