# Generated by Django 5.2.9 on 2025-12-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0026_remove_normalizedpricingdata_normalized__provide_120948_idx'),
    ]

    operations = [
        migrations.RunSQL(
            sql=open('cloud_pricing/sql/normalize_price_unit.sql').read(),
            reverse_sql='DROP FUNCTION IF EXISTS normalize_price_unit(text);'
        ),
    ]
