# Generated by Django 5.2.9 on 2025-12-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0027_auto_20251210_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='unit_amount',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Numeric amount extracted from price unit (e.g. 100 in '100 GB Seconds')", max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='unit_base',
            field=models.CharField(blank=True, help_text='Base unit (e.g., GB, APIRequest, Count, token)', max_length=100),
        ),
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='unit_modifier',
            field=models.CharField(blank=True, help_text="Optional modifier (e.g., 'Lambda' in Lambda-GB-Second)", max_length=100),
        ),
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='unit_notes',
            field=models.CharField(blank=True, help_text='Additional normalization notes: region codes, composite flags, etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='unit_period',
            field=models.CharField(blank=True, help_text='Period component if applicable (e.g., hour, second, month)', max_length=50),
        ),
    ]
