# Generated by Django 5.2.9 on 2025-12-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0028_normalizedpricingdata_unit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedpricingdata',
            name='unit_base',
            field=models.CharField(blank=True, help_text='Base unit (e.g., GB, APIRequest, Count, token)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='normalizedpricingdata',
            name='unit_modifier',
            field=models.CharField(blank=True, help_text="Optional modifier (e.g., 'Lambda' in Lambda-GB-Second)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='normalizedpricingdata',
            name='unit_notes',
            field=models.CharField(blank=True, help_text='Additional normalization notes: region codes, composite flags, etc.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='normalizedpricingdata',
            name='unit_period',
            field=models.CharField(blank=True, help_text='Period component if applicable (e.g., hour, second, month)', max_length=50, null=True),
        ),
    ]
