# Generated by Django 5.2.9 on 2025-12-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0029_alter_normalizedpricingdata_unit_base_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='normalizedpricingdata',
            name='idx_npd_unique_combo',
        ),
        migrations.RemoveField(
            model_name='normalizedpricingdata',
            name='unit_amount',
        ),
        migrations.RemoveField(
            model_name='normalizedpricingdata',
            name='unit_base',
        ),
        migrations.RemoveField(
            model_name='normalizedpricingdata',
            name='unit_modifier',
        ),
        migrations.RemoveField(
            model_name='normalizedpricingdata',
            name='unit_notes',
        ),
        migrations.RemoveField(
            model_name='normalizedpricingdata',
            name='unit_period',
        ),
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='memory_gb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='vcpu_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='normalizedpricingdata',
            constraint=models.UniqueConstraint(fields=('provider', 'service', 'region', 'pricing_model', 'currency', 'product_family', 'instance_type', 'operating_system', 'tenancy', 'price_unit'), name='uniq_npd_conflict_upsert'),
        ),
    ]
