# Generated by Django 5.2.9 on 2025-12-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0030_remove_normalizedpricingdata_idx_npd_unique_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='storage_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
