# Generated by Django 5.2.9 on 2025-12-10 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0031_normalizedpricingdata_storage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedpricingdata',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
