# Generated by Django 5.2.9 on 2025-12-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0032_alter_normalizedpricingdata_effective_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='normalizedpricingdata',
            name='uniq_npd_conflict_upsert',
        ),
        migrations.AddConstraint(
            model_name='normalizedpricingdata',
            constraint=models.UniqueConstraint(fields=('provider', 'service', 'region', 'pricing_model', 'currency', 'product_family', 'instance_type', 'operating_system', 'tenancy', 'price_unit', 'vcpu_count', 'memory_gb', 'storage_type', 'term_length'), name='uniq_npd_conflict_upsert'),
        ),
    ]
