# Generated by Django 5.2.9 on 2025-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0034_remove_normalizedpricingdata_uniq_npd_conflict_upsert_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='normalizedpricingdata',
            name='uniq_npd_conflict_upsert',
        ),
        migrations.AlterField(
            model_name='normalizedpricingdata',
            name='storage_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
