# Generated by Django 5.2.9 on 2025-12-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0035_remove_normalizedpricingdata_uniq_npd_conflict_upsert_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalizedpricingdata',
            old_name='term_length',
            new_name='term_length_year',
        ),
    ]
