# Generated by Django 5.2.9 on 2025-12-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0036_rename_term_length_normalizedpricingdata_term_length_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='domain_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
