# Generated by Django 5.2.9 on 2025-12-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0037_normalizedpricingdata_domain_label copy'),
    ]

    operations = [
        migrations.RunSQL(
            sql=open('cloud_pricing/sql/generate_domain_label.sql').read(),
            reverse_sql='DROP FUNCTION IF EXISTS classify_domain(text);'
        ),
    ]

