# Generated by Django 5.2.9 on 2025-12-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0038_auto_20251212_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawpricingdata',
            name='normalized',
        ),
        migrations.AddConstraint(
            model_name='normalizedpricingdata',
            constraint=models.UniqueConstraint(fields=('provider', 'service', 'region', 'pricing_model', 'currency', 'product_family', 'instance_type', 'operating_system', 'tenancy', 'price_unit'), name='unique_normalized_pricing_entry'),
        ),
    ]
