# Generated by Django 5.2.9 on 2025-12-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0039_remove_rawpricingdata_normalized_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='normalizedpricingdata',
            name='unique_normalized_pricing_entry',
        ),
        migrations.AddConstraint(
            model_name='normalizedpricingdata',
            constraint=models.UniqueConstraint(fields=('provider', 'service', 'region', 'pricing_model', 'currency', 'product_family', 'instance_type', 'operating_system', 'tenancy', 'price_unit', 'effective_date', 'vcpu_count', 'memory_gb', 'storage_type', 'domain_label'), name='unique_normalized_pricing_entry'),
        ),
    ]
