# Generated by Django 5.2.9 on 2025-12-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0040_remove_normalizedpricingdata_unique_normalized_pricing_entry_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='normalizedpricingdata',
            name='unique_normalized_pricing_entry',
        ),
        migrations.RemoveIndex(
            model_name='normalizedpricingdata',
            name='idx_npd_price_change_detection',
        ),
    ]
