# Generated by Django 5.2.9 on 2025-12-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0041_remove_normalizedpricingdata_unique_normalized_pricing_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='effective_price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
