# Generated by Django 5.2.9 on 2025-12-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0042_normalizedpricingdata_effective_price_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedpricingdata',
            name='price_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
