# Generated by Django 5.2.9 on 2025-12-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0043_alter_normalizedpricingdata_price_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='is_all_upfront',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='is_no_upfront',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='is_partial_upfront',
            field=models.BooleanField(default=False),
        ),
    ]
