# Generated by Django 5.2.9 on 2025-12-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0044_normalizedpricingdata_is_all_upfront_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalizedpricingdata',
            name='term_length_year',
        ),
        migrations.AddField(
            model_name='normalizedpricingdata',
            name='term_length_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
