# Generated by Django 5.2.9 on 2025-12-13 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0045_remove_normalizedpricingdata_term_length_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedpricingdata',
            name='pricing_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud_pricing.pricingmodel'),
        ),
    ]
