# Generated by Django 5.2.9 on 2026-01-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0046_alter_normalizedpricingdata_pricing_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceHistory',
        ),
    ]
