# Generated by Django 5.2.9 on 2026-01-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0047_delete_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicalllog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apicalllog',
            name='duration_seconds',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Time taken to complete the operation in seconds', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apicalllog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if operation failed', null=True),
        ),
        migrations.AddField(
            model_name='apicalllog',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata about the operation (JSON format)', null=True),
        ),
        migrations.AddField(
            model_name='apicalllog',
            name='normalization_success_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of records successfully normalized (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='apicalllog',
            name='records_failed',
            field=models.IntegerField(default=0, help_text='Number of records that failed processing'),
        ),
        migrations.AddField(
            model_name='apicalllog',
            name='records_inserted',
            field=models.IntegerField(default=0, help_text='Number of new records created'),
        ),
        migrations.AddField(
            model_name='apicalllog',
            name='records_processed',
            field=models.IntegerField(default=0, help_text='Total number of records processed'),
        ),
        migrations.AddField(
            model_name='apicalllog',
            name='throughput_records_per_second',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of records processed per second', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='apicalllog',
            name='api_endpoint',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apicalllog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['called_at'], name='cloud_prici_called__9fe0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['-called_at'], name='cloud_prici_called__ee081f_idx'),
        ),
    ]
