# Generated by Django 5.2.9 on 2026-01-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_pricing', '0048_apicalllog_completed_at_apicalllog_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='normalizedpricingdata',
            index=models.Index(fields=['is_active', 'region', 'operating_system', 'vcpu_count', 'memory_gb', 'effective_date'], name='idx_npd_matching'),
        ),
    ]
